version: '3.8'

services:
  # База даних
  db:
    image: postgres:latest
    container_name: coursework_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: shop_db
    ports:
      - "5433:5432"
    volumes:
      # Шлях до міграцій (перевірте, чи папка називається migrations чи Migrations)
      - ./migrations/001_initial.sql:/docker-entrypoint-initdb.d/001_initial.sql
      - ./migrations/002_seed_data.sql:/docker-entrypoint-initdb.d/002_seed_data.sql 
  # Ваш C# додаток
  backend:
    image: coursework-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coursework_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Підключення до "db" замість "localhost"
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=shop_db;Username=admin;Password=password123