version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: coursework_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: shop_db
    ports:
      - "5433:5432"
    volumes:
      - ./migrations/001_initial.sql:/docker-entrypoint-initdb.d/001_initial.sqlsss